In [3]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128),
                    CenteredLayer())

In [7]:
Y = net(torch.rand(4, 8))
# print(Y)
Y.mean()

tensor(3.7253e-09, grad_fn=<MeanBackward0>)

In [8]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.rand(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [9]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.1350,  0.6497,  1.8432],
        [ 0.5462, -0.2207, -0.5462],
        [-0.7559, -0.3471,  1.0473],
        [-1.4914,  0.8328,  1.8084],
        [-1.1992, -2.7411,  0.4006]], requires_grad=True)

In [10]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0432, 3.1060],
        [0.0000, 0.0000, 3.0536]])

In [11]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])