In [33]:
!nvidia-smi
torch.cuda.device_count()

Tue Sep 30 17:55:12 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   73C    P0             28W /  114W |    1220MiB /   6144MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

0

In [1]:
import torch
from torch import nn
torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

In [2]:
print(torch.cuda.is_available())
print(torch.__version__)

True
2.0.0+cu118


In [3]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0


In [4]:
def try_gpu(i=0): 
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus(): 
    devices = [torch.device(f'cuda:{i}')
        for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0)])

In [26]:
!"D:/Program Files/anaconda/install/Scripts/conda.exe" list

# packages in environment at D:\Program Files\anaconda\install\envs\d2l:
#
# Name                    Version                   Build  Channel
anyio                     4.11.0                   pypi_0    pypi
argon2-cffi               25.1.0                   pypi_0    pypi
argon2-cffi-bindings      25.1.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 3.0.0                    pypi_0    pypi
async-lru                 2.0.5                    pypi_0    pypi
attrs                     25.3.0                   pypi_0    pypi
babel                     2.17.0                   pypi_0    pypi
beautifulsoup4            4.14.0                   pypi_0    pypi
bleach                    6.2.0                    pypi_0    pypi
bzip2                     1.0.8                h2bbff1b_6    defaults
ca-certificates           2025.9.9             haa95532_0    defaults
certifi                   2025.8.3                 pypi_0 

In [27]:
!pip install torch==2.0.0+cu118 torchvision==0.15.0+cu118 torchaudio==2.0.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     ---------------------------------------- 0.0/2.6 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.6 GB 6.3 MB/s eta 0:06:55
     ---------------------------------------- 0.0/2.6 GB 6.9 MB/s eta 0:06:20
     ---------------------------------------- 0.0/2.6 GB 7.3 MB/s eta 0:06:00
     ---------------------------------------- 0.0/2.6 GB 7.7 MB/s eta 0:05:38
     ---------------------------------------- 0.0/2.6 GB 8.3 MB/s eta 0:05:16
     ---------------------------------------- 0.0/2.6 GB 8.8 MB/s eta 0:04:55
     ---------------------------------------- 0.0/2.6 GB 9.2 MB/s eta 0:04:42
     ---------------------------------------- 0.0/2.6 GB 9.5 MB/s eta 0:04:33
     ---------------------------------------- 0.0/2.6 GB 9.7 MB/s eta 0:04:29
     ---------------------------------------- 0.0/2.6 GB 9.9 MB/s eta 0:04:21
     ---------------------------------------- 0.0/2.6 GB 10.0 MB/s eta 0:04:19
 

  You can safely remove it manually.


In [5]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [6]:
X = torch.ones(2, 3, device = try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [13]:
Y = torch.rand(2, 3, device=try_gpu(0))
Y

tensor([[0.9909, 0.3576, 0.5169],
        [0.9589, 0.3791, 0.3853]], device='cuda:0')

In [14]:
Z = X.cuda(0)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [15]:
Y + Z

tensor([[1.9909, 1.3576, 1.5169],
        [1.9589, 1.3791, 1.3853]], device='cuda:0')

In [17]:
Z.cuda(0) is Z

True

In [18]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device = try_gpu())

In [19]:
net(X)

tensor([[0.2236],
        [0.2236]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [20]:
net[0].weight.data.device

device(type='cuda', index=0)