In [7]:
import torch

# requires_grad为是否计算梯度
'''
.grad_fn 就是说该Tensor是不是通过某些运算得到的，若是，则grad_fn返回一个与这些运算相关的对象，否则是None
'''
x = torch.ones(2, 2, requires_grad=True)

y = x + 2
print(x, y)
print(x.grad_fn, y.grad_fn)
#AddBackward0是加法

print(x.is_leaf, y.is_leaf) # True False
#像x这种直接创建的称为叶子节点,而y不是

z = y * x
z1 = y @ x
print(z)
print(z1)
out = z.mean()
print(out, f"\n\nout的grad_fn是{out.grad_fn}\n\n")

print(torch.randn(6).mean().grad_fn)
print(torch.randn(6, requires_grad = True).mean().grad_fn)

#.requires_grad_()方法
a = torch.randn(2, 2)
print(a, f"\n\n{a.mean()}\n\n")
print(a.requires_grad)
print(a.requires_grad_(True).requires_grad)

print(f"\n\n\n{torch.randn(1,)}\n\n{torch.randn(1, 1)}")
print(f"\n\n\n{torch.randn(1,).shape}\n\n{torch.randn(1, 1).shape}")

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
None <AddBackward0 object at 0x000002A4C972C550>
True False
tensor([[3., 3.],
        [3., 3.]], grad_fn=<MulBackward0>)
tensor([[6., 6.],
        [6., 6.]], grad_fn=<MmBackward0>)
tensor(3., grad_fn=<MeanBackward0>) 

out的grad_fn是<MeanBackward0 object at 0x000002A4C972C220>


None
tensor([[ 0.7444,  1.5641],
        [-0.3397,  0.5216]]) 

0.6225787401199341


False
True



tensor([0.6479])

tensor([[-1.2901]])



torch.Size([1])

torch.Size([1, 1])


In [67]:
#标量
# shape是张量的一个属性，size()是张量的一个方法
a = torch.tensor(1., dtype = float, requires_grad = True)# 是一个张量
b = torch.tensor([1], dtype = float, requires_grad = True)
c = torch.rand(1, dtype = float, requires_grad = True)
print(f"\n{a}\n\n{b}\n\n{c}\n")
print(a.size(), b.size(), c.shape)

#梯度
print(a)
a.backward()
out.retain_grad()
print(a.grad)
print(out)
print(out.grad)


1.0

tensor([1.], dtype=torch.float64, requires_grad=True)

tensor([0.1294], dtype=torch.float64, requires_grad=True)

torch.Size([]) torch.Size([1]) torch.Size([1])
tensor(1., dtype=torch.float64, requires_grad=True)
tensor(1., dtype=torch.float64)
tensor(3., grad_fn=<MeanBackward0>)
