In [25]:
import numpy as np

#都是ndarray数据类型

t1 = np.array([1, 2, 3])
print(t1)
print(type(t1))

t2 = np.array(range(3))
print(t2)
print(type(t2))

#和range不同，可以生成小数
t3 = np.arange(1, 4, 0.1)
print(t3)
print(type(t3))

[1 2 3]
<class 'numpy.ndarray'>
[0 1 2]
<class 'numpy.ndarray'>
[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7
 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9]
<class 'numpy.ndarray'>


In [37]:
#dtype是看存放的数据的类型，只能用于ndarray

t4 = np.arange(1, 4, 0.5)
print(type(t4))
print(t4.dtype)
print(t2.dtype)

<class 'numpy.ndarray'>
float64
int64


![数据类型](数据类型.png)

In [75]:
#可以指定类型
t5 = np.arange(1, 4, dtype = float)
print(t5.dtype)

t6 = np.array([1, 1, 0, 1, 0, 1], dtype = bool)
print(t6.dtype)

#astype调整数据类型
t7 = t5.astype("i1")
print(t7.dtype)

#10个从0到1的随机数
t8 = np.random.random(10)
print(t8)
print(t8.dtype)

#round()可以用来取小数(np中的取法)
t9 = np.round(t8, 2)
print(t9)
print(t9.dtype)

float64
bool
int8
[0.03206523 0.42782921 0.80202431 0.78923598 0.18610476 0.16666825
 0.39544036 0.84330325 0.96286375 0.73067157]
float64
[0.03 0.43 0.8  0.79 0.19 0.17 0.4  0.84 0.96 0.73]
float64


In [119]:
#shape方法
a = np.array([[1, 2, 3, 7, 3, 9], [4, 5, 6, 8, 0, 1]])
print(a.shape)

#reshape
b = a.reshape(3, 4)
print(b.shape)

#2块，每一块3行4列 
c = np.arange(24).reshape(2, 3, 4)
print(c)

#reshape是有返回值的，对c不会改变
c.reshape(4, 6)
print(c)

d = c.reshape(24)
print(d)

e = c.reshape(1, 24)
print(e)

#flatten展开
f = c.flatten()
print(f)

(2, 6)
(3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [129]:
#广播机制
g = c.reshape(4, 6)
print(g)
print(g + 2)

#nan是0/0.inf是x(x不=0)/0
#nan表示不是数字，inf表示无穷
print(g / 0)

k1 = np.random.random(9)
k2 = np.random.random(9)
k1_1 = k1.reshape(3, 3)
k2_1 = k2.reshape(3, 3)
print(k1_1, k2_1)
#和矩阵相乘不一样
print(k1_1 * k2_1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]]
[[nan inf inf inf inf inf]
 [inf inf inf inf inf inf]
 [inf inf inf inf inf inf]
 [inf inf inf inf inf inf]]
[[0.8500452  0.1491979  0.16775777]
 [0.17789733 0.55314607 0.42405078]
 [0.50144287 0.03425763 0.02395635]] [[0.52931573 0.20078482 0.21531468]
 [0.38839363 0.10930718 0.69755324]
 [0.72398808 0.62349412 0.90735538]]
[[0.4499423  0.02995667 0.03612071]
 [0.06909419 0.06046284 0.295798  ]
 [0.36303866 0.02135943 0.02173693]]


C:\Users\a1867\AppData\Local\Temp\ipykernel_26060\2982021560.py:8: RuntimeWarning: divide by zero encountered in divide
  print(g / 0)
C:\Users\a1867\AppData\Local\Temp\ipykernel_26060\2982021560.py:8: RuntimeWarning: invalid value encountered in divide
  print(g / 0)


In [131]:
#仍然是广播机制
m = np.arange(24).reshape(6, 4)
n = np.arange(6).reshape(6, 1)
print(m - n) 

#另外，比如shape(3, 3, 2)和(3, 2)是可以计算的

[[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]
 [12 13 14 15]
 [15 16 17 18]]
