In [43]:
import torch
x = torch.empty(5, 3)
print(x)

tensor([[1.5231e+23, 1.8777e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [45]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0569, 0.8989, 0.7236],
        [0.7163, 0.6939, 0.9698],
        [0.2816, 0.5034, 0.5185],
        [0.5709, 0.7204, 0.7111],
        [0.3009, 0.0523, 0.5973]])


In [47]:
#-2^63 到 2^63 - 1，大整数
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [49]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [81]:
y = torch.zeros(4, 2, dtype=torch.long)
print(y, y.dtype)

#返回的tensor默认具有相同的torch.dtype和torch.device(如果不重新指定)
y1 = y.new_ones(5, 3, dtype=torch.float64)
print(y1, y1.dtype)

#z = torch.randn_like(6, 4, dtype=torch.float)
z = torch.randn_like(x, dtype=torch.float)
print(z, z.dtype, z.size(), z.shape)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]]) torch.int64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.float64
tensor([0.3969, 0.9037]) torch.float32 torch.Size([2]) torch.Size([2])


In [103]:
print(x)
a = x.new_ones(5,3)
print(a)
b = torch.rand(5,3)
print(b)
print(a + b)
print(torch.add(a, b))

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.0764, 0.9861, 0.5350],
        [0.9027, 0.8712, 0.0149],
        [0.1550, 0.0577, 0.3257],
        [0.8690, 0.7379, 0.0537],
        [0.8388, 0.9227, 0.2912]])
tensor([[1.0764, 1.9861, 1.5350],
        [1.9027, 1.8712, 1.0149],
        [1.1550, 1.0577, 1.3257],
        [1.8690, 1.7379, 1.0537],
        [1.8388, 1.9227, 1.2912]])
tensor([[1.0764, 1.9861, 1.5350],
        [1.9027, 1.8712, 1.0149],
        [1.1550, 1.0577, 1.3257],
        [1.8690, 1.7379, 1.0537],
        [1.8388, 1.9227, 1.2912]])


In [ ]:
#广播
print(y, torch.add(x, y))